name: Release with GitHub CLI

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    tags:
      - "v*"  # Triggers when a tag starting with "v" is pushed

jobs:
  release:
    runs-on: windows-latest
    steps:
      # 1. Checkout your repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Check that GitHub CLI is available (optional, for debugging)
      - name: Check GitHub CLI version
        run: gh --version

      # 3. Build your Rust project in release mode
      - name: Build binary
        run: cargo build --release

      # 4. Package your binary into a zip file
      - name: Package binary
        run: |
          mkdir release
          cp target/release/Rusty-Analyser release/
          cd release
          zip Rusty-Analyser.zip Rusty-Analyser

      # 5. Create a GitHub release and upload the packaged binary using GitHub CLI
      - name: Create Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" release/Rusty-Analyser.zip \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release for tag ${{ github.ref_name }}"
