name: Release with GitHub CLI

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    tags:
      - "v*"  # Triggers when a tag starting with "v" is pushed

jobs:
  release:
    runs-on: windows-latest
    steps:
      # 1. Checkout your repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Verify GitHub CLI is available (optional)
      - name: Check GitHub CLI version
        run: gh --version
        shell: bash

      # 3. Build your Rust project for Windows (MSVC target)
      - name: Build binary
        run: cargo build --release --target=x86_64-pc-windows-msvc
        shell: bash

      # 4. Package your binary into a zip file
      - name: Package binary
        run: |
          mkdir release
          cp target/x86_64-pc-windows-msvc/release/Rusty-Analyser.exe release/
          cd release
          zip Rusty-Analyser.zip Rusty-Analyser.exe
        shell: bash

      # 5. Create a GitHub release and upload the asset using GitHub CLI
      - name: Create Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" release/Rusty-Analyser.zip \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release for tag ${{ github.ref_name }}"
        shell: bash
